--- #YAML:1.0
name:               Object-InsideOut
version:            3.75
abstract:           Comprehensive inside-out object support module
author:
    - Jerry D. Hedden <jdhedden AT cpan DOT org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    attributes:        0
    B:                 0
    Config:            0
    Data::Dumper:      0
    Exception::Class:  1.29
    overload:          0
    Scalar::Util:      1.23
    strict:            0
    Test::More:        0.5
    warnings:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
recommends:
    Math::Random::MT::Auto: 5.04
    Want: 0.12
