--- #YAML:1.0
name:                Object-InsideOut
version:             3.06
abstract:            Comprehensive inside-out object support module
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    attributes:                    0
    B:                             0
    Config:                        0
    Data::Dumper:                  0
    Exception::Class:              1.22
    overload:                      0
    Scalar::Util:                  1.19
    strict:                        0
    Test::More:                    0.5
    warnings:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Jerry D. Hedden <jdhedden AT cpan DOT org>
