# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Object-InsideOut
version:      1.12
version_from: lib/Object/InsideOut.pm
installdirs:  site
requires:
    attributes:                    0
    Data::Dumper:                  0
    Exception::Class:              1.22
    overload:                      0
    Scalar::Util:                  1.1
    Test::More:                    0.5

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
