--- #YAML:1.0
name:                Object-InsideOut
version:             2.03
abstract:            Comprehensive inside-out object support module
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.30_04
author:              Jerry D. Hedden <jdhedden AT cpan DOT org>
distribution_type:   module
requires:     
    attributes:                    0
    B:                             0
    Config:                        0
    Data::Dumper:                  0
    Exception::Class:              1.22
    overload:                      0
    Scalar::Util:                  1.18
    strict:                        0
    Test::More:                    0.5
    warnings:                      0
meta-spec:
    url: http://module-build.sourceforge.net/META-spec-new.html
    version: 1.1
